import re 


# to remove big para explanation stuff at start of any file
def remove_header_banners(text):
    lines = text.splitlines()
    skipping = True
    cleaned = []

    for line in lines:
        stripped = line.strip()
        if skipping:
            if stripped.startswith(("#", "//", "/*", "*", "*/", "--")):
                continue
            if stripped == "":
                continue
            skipping = False
        cleaned.append(line)
    
    return "\n".join(cleaned)

# detecting autogenrated files (no use for apna model)
def is_generated_files(text):

    GENERATED_MARKERS = [
        "auto-generated",
        "generated by",
        "do not edit",
        "autogenerated",
        "@generated"
    ]

    lower = text.lower()
    return any(marker in lower for marker in GENERATED_MARKERS)


def is_minified(text):

    lines = text.splitlines()

    if len(lines) <= 2 :
        avg_line_length = sum( len(l)  for l in lines )/ max(1, len(lines))
        return avg_line_length > 500
    return False

# whitespace removal 
def normalize_whitespace(text):
   
    # Convert CRLF to LF
    text = text.replace("\r\n", "\n")

    # Remove trailing spaces
    text = "\n".join(line.rstrip() for line in text.splitlines())

    # Remove multiple blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()

def clean_file_content(text):
    
    if not text or len(text.strip()) == 0:
        return None
    
    text = remove_header_banners(text)

    if is_generated_files(text):
        return None
    
    if is_minified(text):
        return None
    
    text = normalize_whitespace(text)
    
    if len(text) < 20 :
        return None
    
    return text  